export const projects = [
    {
        id: 1,
        project_title: 'Sample Project 1',
        project_poc: 'Jane Doe',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member1.com.ph',
        project_type: 'Webinar',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Metro Manila',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 2,
        project_title: 'Sample Project 2',
        project_poc: 'Jane Doe',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member2.com.ph',
        project_type: 'Webinar',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Metro Manila',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 3,
        project_title: 'Sample Project 3',
        project_poc: 'Jane Doe',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member3.com.ph',
        project_type: 'Webinar',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Metro Manila',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 4,
        project_title: 'Sample Project 4',
        project_poc: 'Jane Doe',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member4.com.ph',
        project_type: 'Webinar',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Metro Manila',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 5,
        project_title: 'Sample Project 5',
        project_poc: 'Jane Doe',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member5.com.ph',
        project_type: 'Webinar',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Metro Manila',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 6,
        project_title: 'Sample Project 6',
        project_poc: 'Jane Doe',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member6.com.ph',
        project_type: 'Webinar',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Metro Manila',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    
]