export const projects = [
    {
        id: 1,
        project_title: 'Sample Project 1',
        project_poc: 'Clementine Bauch',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member1.com.ph',
        project_type: 'Webinar',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Gender Equality',
        project_location: 'Metro Manila',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 2,
        project_title: 'Sample Project 2',
        project_poc: 'Ervin Howell',
        project_pocnum: '09198765432',
        project_pocemail: 'arise@member2.com.ph',
        project_type: 'Training',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Cebu City',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 3,
        project_title: 'Sample Project 3',
        project_poc: 'Patricia Lebsack',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member3.com.ph',
        project_type: 'Media Campaign',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Climate Action',
        project_location: 'Zamboanga City',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 4,
        project_title: 'Sample Project 4',
        project_poc: 'Chelsey Dietrich',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member4.com.ph',
        project_type: 'Dialogue',
        project_status: 'Completed',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Zero Hunger',
        project_location: 'Quezon Province',
        project_tstart: '02/02/2020',
        project_tend: '02/08/2020',
        project_astart: '02/02/2020',
        project_aend: '02/08/2020',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 5,
        project_title: 'Sample Project 5',
        project_poc: 'Leanne Graham',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member5.com.ph',
        project_type: 'Media Campaign',
        project_status: 'Started',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'Quality Education',
        project_location: 'Metro Manila',
        project_tstart: '11/12/2020',
        project_tend: '12/10/2020',
        project_astart: ' ',
        project_aend: ' ',
        project_tpeople: '50',
        project_apeople: '35'
    },
    {
        id: 6,
        project_title: 'Sample Project 6',
        project_poc: 'Kurtis Weissnat',
        project_pocnum: '09123456789',
        project_pocemail: 'arise@member6.com.ph',
        project_type: 'Fundraiser',
        project_status: 'Ongoing',
        project_desc: 'This is sample project. This is a webinar.',
        sdgt_name: 'No Poverty',
        project_location: 'Cordillera Province',
        project_tstart: '11/02/2020',
        project_tend: '12/08/2020',
        project_astart: ' ',
        project_aend: ' ',
        project_tpeople: '50',
        project_apeople: '35'
    },
    
]